### ISSUE TITLE
Ugly Template controller

### ISSUE THREAD

**Issue by sushant12** [sushant12/fuitter#8]
Right now the template controller is very ugly. Modularize the code.

**Comment by wikimatze** [comment]
I don't see the reason for the template controller => even what suggest the name? Which template does it renders? The methods `save_albums` and other methods does not have something to do with template. Some other controllers and modules lurks in this big thing.

**Comment by sushant12** [comment]
I did move the methods to a template helper and marked `save_albums` and other such methods as private. Template is the first thing that came into my mind. What should I name it to? @wikimatze

**Comment by wikimatze** [comment]
Look at the methods:

```ruby
      def get_data_for_home
        facebook_page = FacebookPage.find(id: params['id'])
        facebook_page.about ? facebook_page : nil
      end

      def get_data_for_news
        facebook_page = FacebookPage.find(id: params['id'])
        page_feed = facebook_page.page_feeds
        page_feed.empty?? nil : page_feed
      end

      def get_data_for_about
        get_data_for_home
      end

      def get_data_for_contact
        get_data_for_home
      end

      def get_data_for_gallery
        facebook_page = FacebookPage.find(id: params[:id])
        albums = facebook_page.albums
        albums.empty? ? nil : albums
      end

      def list_photos
        album = Album.find(id: params[:album_id])
        album.pictures
      end

      def get_albums_from_api(obj)
        save_albums(obj.get_connection('me','albums'), obj)
      end

      def get_data_from_api(obj)
        fields = {fields: 'about,description_html,cover,link,location,website'}
        save_common_page_field (obj.get_object('me',fields))
      end

      def get_page_feed_from_api(obj)
        fields = ['created_time','description','name','attachments']
        save_page_feed (obj.get_connection('me','feed',{fields: fields}))
      end
```

What emerging name can you think of?

**Comment by wikimatze** [comment]
I have `FacebookData` or `FacebookInformationController` in mind.

**Comment by sushant12** [comment]
I was thinking of Dispatcher but your`s make sense

**Comment by sushant12** [comment]
@wikimatze how abt adding those api req methods in `FacebookData helper` and rename template controller to `PageController` . I will save `TemplateController` for later when the user will have the option to chose differnt templates to render the fb data into

**Comment by wikimatze** [comment]
Sounds good for me. With the `Dispatcher` I'm thinking of Subscriber/Listener pattern - don't use that name.
